export const AGENT_MESSAGE = 'agent_message'
export const FUNCTION_CALL = 'function_call'
export const CUSTOM_TOOL_CALL = 'custom_tool_call'
export const QUESTION = 'question'
export const ANSWER = 'answer'
export const WEB_SEARCH_CALL = 'web_search_call'
export const USER_MESSAGE = 'user_message'
